apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jzo4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xrwl-tenant/rhtap-demo-app/hacbs-test-project-jzo4@sha256:6fd20680548d2fbebc1bec36c866e6fb7763b61b7b854044eef5902f773f14cc
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
